import React, { useState } from "react";
import {
  View,
  Text,
  StyleSheet,
  Button,
  ScrollView,
  TouchableOpacity,
  Alert,
} from "react-native";
import {
  Table,
  TableWrapper,
  Row,
  Rows,
  Col,
  Cols,
  Cell,
} from "react-native-table-component";

const Show = ({ navigation }) => {
  const [tableHead, setTableHead] = useState([
    "Date",
    "Invoice No",
    "Name",
    "Address",
    "Email",
    "Mobile",
    "QTY",
    "Product",
    "Product Price",
    "Order Update",
    "Delivery Charge",
    "Delivery Company",
    "Remarks",
    "1st Followup",
    "2nd Followup",
    "3rd Followup",
    "bKash Cost",
    "Others (VAT, TAX, etc.)",
    "Deposit to Accounts",
    "Action",
  ]);
  const [tableData, setTableData] = useState([
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
    [
      "2022-10-27",
      "6",
      "Arafat hossain",
      "Gulshan-1, Dhaka",
      "abc@gmail.com",
      "0177776666555",
      "3",
      "Head Phone",
      "1020",
      "500",
      "Delivered",
      "75",
      "RedX",
      "Nothing",
      "Processing",
      "N/A",
      "N/A",
      "20",
      "10",
      "800",
    ],
  ]);

  const alertIndex = (index) => {
    Alert.alert(`This is row ${index + 1}`);
  };

  const element = (data, index) => (
    <TouchableOpacity onPress={() => alertIndex(index)}>
      <View style={styles.btn}>
        <Text style={styles.btnText}>button</Text>
      </View>
    </TouchableOpacity>
  );

  return (
    <View style={styles.container}>
      <ScrollView horizontal={true}>
        <ScrollView vertical={true}>
          <Table borderStyle={{ borderColor: "blue", borderWidth: 0.5 }}>
            <Row data={tableHead} style={styles.head} textStyle={styles.text} />
            {tableData.map((rowData, index) => (
              <TableWrapper key={index} style={styles.row}>
                {rowData.map((cellData, cellIndex) => (
                  <Cell
                    key={cellIndex}
                    data={
                      cellIndex === 19 ? element(cellData, index) : cellData
                    }
                    textStyle={styles.text}
                  />
                ))}
              </TableWrapper>
            ))}
          </Table>
        </ScrollView>
      </ScrollView>
      {/* <Text style={styles.text}>Show Item</Text>
      <Button
        onPress={() => navigation.navigate("Update")}
        title="Move to Update screen"
      /> */}
    </View>
  );
};

// const styles = StyleSheet.create({
//   container: {
//     flex: 1,
//     justifyContent: "center",
//     alignItems: "center",
//     backgroundColor: "#fff",
//   },
//   text: {
//     fontSize: 20,
//     fontWeight: "bold",
//     color: "#000",
//   },
// });

const styles = StyleSheet.create({
  container: { flex: 1, padding: 16, paddingTop: 30, backgroundColor: "#fff" },
  head: { height: 40, backgroundColor: "#808B97" },
  text: { margin: 6 },
  row: { flexDirection: "row", backgroundColor: "#F0F1C1" },
  btn: { width: 58, height: 18, backgroundColor: "#78B7BB", borderRadius: 2 },
  btnText: { textAlign: "center", color: "#fff" },
});
export default Show;
